### ISSUE TITLE
Changes to scss @imports do not break cache

### ISSUE THREAD

**Issue by chasegiunta** [aelvan/AutoMin-Craft#8]
Cannot figure out why this is. I'm importing 3 other .scss files into my `main.scss`

```
@import '_dashboard.scss';
@import '_general.scss';
@import '_misc.scss';
```

Edits to these files do not trigger a cache-break. If I edit my `main.scss` that _does_ trigger a cache-break, shows the new changes in my @imports, and works as expected.

Just to troubleshoot, I've tried removing the underscore prefix to the imports, and have also updated the very outdated scssphp library to the latest build.

**Comment by chasegiunta** [comment]
oh hey. this is a known thing.

> When using @import though, updating files that is imported into your base scss file will not automatically invalidate the cache.

**Comment by chasegiunta** [comment]
So I forked the project and made this happen. It could be done a little better, but it'll work for now. https://github.com/ChaseGiunta/AutoMin-Craft

**Comment by aelvan** [comment]
If you create a pull request, I'll be happy to merge it.

**Comment by chasegiunta** [comment]
Probably not for public consumption yet. Doesn't support multiple include paths, doesn't use any of Jesse's functions (it probably could), and it could also trigger cache rebuilding through one of Jesse's functions, instead of what it's doing now (changing modified time on passed scss files). Once I get a chance to update it, I'll submit a PR.
